### ISSUE TITLE
Add basic integration test for CMMN modeling

### ISSUE THREAD

**Issue by nikku** [bpmn-io/cmmn-js#43]
- [ ] move sentry between scopes
- [ ] morph task to different one
- [ ] model simple case
### Tasks
- [ ] create integration test suite based on bpmn-io/bpmn-js-integration
- [ ] add test cases
- [ ] use cmmn-js-cli _?_
